# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.runs/synth_1/rvfpgaboolean.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param general.maxThreads 8
set_param chipscope.maxJobs 4
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7s50csga324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.cache/wt [current_project]
set_property parent.project_path D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
set_property include_dirs {
  D:/Fall_2023/ECE_540/HW1/lab5/RVfpga_EL2/RVfpga_Boolean/src/OtherSources/pulp-platform.org__common_cells_1.20.0/include
  D:/Fall_2023/ECE_540/HW1/lab5/RVfpga_EL2/RVfpga_Boolean/src/VeeRwolf/Interconnect/AxiInterconnect/pulp-platform.org__axi_0.25.0/include
} [current_fileset]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog {
  D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/sources_1/imports/src/VeeRwolf/VeeR_EL2CoreComplex/include/common_defines.vh
  D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/sources_1/imports/src/VeeRwolf/Peripherals/gpio/gpio_defines.v
  D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/sources_1/imports/src/VeeRwolf/Peripherals/ptc/ptc_defines.v
  D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/sources_1/imports/src/VeeRwolf/Peripherals/uart/uart_defines.v
  D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/sources_1/imports/src/VeeRwolf/Interconnect/AxiInterconnect/axi_intercon.vh
  D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/sources_1/imports/src/VeeRwolf/Interconnect/WishboneInterconnect/wb_intercon-1250154467e4a5658043f4be3945fc15a7808551/sw/wb_intercon.vh
  D:/Fall_2023/ECE_540/HW1/lab5/RVfpga_EL2/RVfpga_Boolean/src/OtherSources/pulp-platform.org__common_cells_1.20.0/include/common_cells/registers.svh
  D:/Fall_2023/ECE_540/HW1/lab5/RVfpga_EL2/RVfpga_Boolean/src/VeeRwolf/Interconnect/AxiInterconnect/pulp-platform.org__axi_0.25.0/include/axi/assign.svh
  D:/Fall_2023/ECE_540/HW1/lab5/RVfpga_EL2/RVfpga_Boolean/src/VeeRwolf/Interconnect/AxiInterconnect/pulp-platform.org__axi_0.25.0/include/axi/typedef.svh
  D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/sources_1/imports/src/VeeRwolf/VeeR_EL2CoreComplex/include/el2_param.vh
  D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/sources_1/imports/src/VeeRwolf/VeeR_EL2CoreComplex/include/pic_map_auto.h
}
set_property is_global_include true [get_files D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/sources_1/imports/src/VeeRwolf/VeeR_EL2CoreComplex/include/common_defines.vh]
set_property file_type "Verilog Header" [get_files D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/sources_1/imports/src/VeeRwolf/Peripherals/gpio/gpio_defines.v]
set_property file_type "Verilog Header" [get_files D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/sources_1/imports/src/VeeRwolf/Peripherals/ptc/ptc_defines.v]
set_property file_type "Verilog Header" [get_files D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/sources_1/imports/src/VeeRwolf/Peripherals/uart/uart_defines.v]
set_property file_type "Verilog Header" [get_files D:/Fall_2023/ECE_540/HW1/lab5/RVfpga_EL2/RVfpga_Boolean/src/OtherSources/pulp-platform.org__common_cells_1.20.0/include/common_cells/registers.svh]
set_property file_type "Verilog Header" [get_files D:/Fall_2023/ECE_540/HW1/lab5/RVfpga_EL2/RVfpga_Boolean/src/VeeRwolf/Interconnect/AxiInterconnect/pulp-platform.org__axi_0.25.0/include/axi/assign.svh]
set_property file_type "Verilog Header" [get_files D:/Fall_2023/ECE_540/HW1/lab5/RVfpga_EL2/RVfpga_Boolean/src/VeeRwolf/Interconnect/AxiInterconnect/pulp-platform.org__axi_0.25.0/include/axi/typedef.svh]
set_property file_type "Verilog Header" [get_files D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/sources_1/imports/src/VeeRwolf/VeeR_EL2CoreComplex/include/pic_map_auto.h]
read_mem D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/sources_1/imports/src/VeeRwolf/BootROM/sw/boot_main.mem
read_verilog -library xil_defaultlib -sv {
  D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/sources_1/imports/src/VeeRwolf/VeeR_EL2CoreComplex/include/el2_pdef.vh
  D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/sources_1/imports/src/VeeRwolf/Peripherals/vga/CHAR_ROM.sv
  D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/sources_1/imports/src/OtherSources/pulp-platform.org__common_cells_1.20.0/src/cf_math_pkg.sv
  D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/sources_1/imports/src/OtherSources/pulp-platform.org__common_cells_1.20.0/src/addr_decode.sv
  D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/sources_1/imports/src/VeeRwolf/Interconnect/AxiInterconnect/pulp-platform.org__axi_0.25.0/src/axi_pkg.sv
  D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/sources_1/imports/src/VeeRwolf/Interconnect/AxiInterconnect/pulp-platform.org__axi_0.25.0/src/axi_demux.sv
  D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/sources_1/imports/src/VeeRwolf/Interconnect/AxiInterconnect/pulp-platform.org__axi_0.25.0/src/axi_err_slv.sv
  D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/sources_1/imports/src/VeeRwolf/Interconnect/AxiInterconnect/pulp-platform.org__axi_0.25.0/src/axi_id_prepend.sv
  D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/sources_1/imports/src/VeeRwolf/Interconnect/AxiInterconnect/axi_intercon.sv
  D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/sources_1/imports/src/VeeRwolf/Interconnect/AxiInterconnect/pulp-platform.org__axi_0.25.0/src/axi_intf.sv
  D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/sources_1/imports/src/VeeRwolf/Interconnect/AxiInterconnect/pulp-platform.org__axi_0.25.0/src/axi_mux.sv
  D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/sources_1/imports/src/VeeRwolf/Interconnect/AxiInterconnect/pulp-platform.org__axi_0.25.0/src/axi_xbar.sv
  D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/sources_1/imports/src/VeeRwolf/VeeR_EL2CoreComplex/lib/beh_lib.sv
  D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/sources_1/imports/src/OtherSources/bscan_tap.sv
  D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/sources_1/imports/src/OtherSources/pulp-platform.org__common_cells_1.20.0/src/counter.sv
  D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/sources_1/imports/src/OtherSources/pulp-platform.org__common_cells_1.20.0/src/delta_counter.sv
  D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/sources_1/imports/src/VeeRwolf/VeeR_EL2CoreComplex/include/el2_def.sv
  D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/sources_1/imports/src/VeeRwolf/VeeR_EL2CoreComplex/dbg/el2_dbg.sv
  D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/sources_1/imports/src/VeeRwolf/VeeR_EL2CoreComplex/dec/el2_dec.sv
  D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/sources_1/imports/src/VeeRwolf/VeeR_EL2CoreComplex/dec/el2_dec_decode_ctl.sv
  D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/sources_1/imports/src/VeeRwolf/VeeR_EL2CoreComplex/dec/el2_dec_gpr_ctl.sv
  D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/sources_1/imports/src/VeeRwolf/VeeR_EL2CoreComplex/dec/el2_dec_ib_ctl.sv
  D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/sources_1/imports/src/VeeRwolf/VeeR_EL2CoreComplex/dec/el2_dec_tlu_ctl.sv
  D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/sources_1/imports/src/VeeRwolf/VeeR_EL2CoreComplex/dec/el2_dec_trigger.sv
  D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/sources_1/imports/src/VeeRwolf/VeeR_EL2CoreComplex/el2_dma_ctrl.sv
  D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/sources_1/imports/src/VeeRwolf/VeeR_EL2CoreComplex/exu/el2_exu.sv
  D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/sources_1/imports/src/VeeRwolf/VeeR_EL2CoreComplex/exu/el2_exu_alu_ctl.sv
  D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/sources_1/imports/src/VeeRwolf/VeeR_EL2CoreComplex/exu/el2_exu_div_ctl.sv
  D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/sources_1/imports/src/VeeRwolf/VeeR_EL2CoreComplex/exu/el2_exu_mul_ctl.sv
  D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/sources_1/imports/src/VeeRwolf/VeeR_EL2CoreComplex/ifu/el2_ifu.sv
  D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/sources_1/imports/src/VeeRwolf/VeeR_EL2CoreComplex/ifu/el2_ifu_aln_ctl.sv
  D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/sources_1/imports/src/VeeRwolf/VeeR_EL2CoreComplex/ifu/el2_ifu_bp_ctl.sv
  D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/sources_1/imports/src/VeeRwolf/VeeR_EL2CoreComplex/ifu/el2_ifu_compress_ctl.sv
  D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/sources_1/imports/src/VeeRwolf/VeeR_EL2CoreComplex/ifu/el2_ifu_ic_mem.sv
  D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/sources_1/imports/src/VeeRwolf/VeeR_EL2CoreComplex/ifu/el2_ifu_iccm_mem.sv
  D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/sources_1/imports/src/VeeRwolf/VeeR_EL2CoreComplex/ifu/el2_ifu_ifc_ctl.sv
  D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/sources_1/imports/src/VeeRwolf/VeeR_EL2CoreComplex/ifu/el2_ifu_mem_ctl.sv
  D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/sources_1/imports/src/VeeRwolf/VeeR_EL2CoreComplex/lib/el2_lib.sv
  D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/sources_1/imports/src/VeeRwolf/VeeR_EL2CoreComplex/lsu/el2_lsu.sv
  D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/sources_1/imports/src/VeeRwolf/VeeR_EL2CoreComplex/lsu/el2_lsu_addrcheck.sv
  D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/sources_1/imports/src/VeeRwolf/VeeR_EL2CoreComplex/lsu/el2_lsu_bus_buffer.sv
  D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/sources_1/imports/src/VeeRwolf/VeeR_EL2CoreComplex/lsu/el2_lsu_bus_intf.sv
  D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/sources_1/imports/src/VeeRwolf/VeeR_EL2CoreComplex/lsu/el2_lsu_clkdomain.sv
  D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/sources_1/imports/src/VeeRwolf/VeeR_EL2CoreComplex/lsu/el2_lsu_dccm_ctl.sv
  D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/sources_1/imports/src/VeeRwolf/VeeR_EL2CoreComplex/lsu/el2_lsu_dccm_mem.sv
  D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/sources_1/imports/src/VeeRwolf/VeeR_EL2CoreComplex/lsu/el2_lsu_ecc.sv
  D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/sources_1/imports/src/VeeRwolf/VeeR_EL2CoreComplex/lsu/el2_lsu_lsc_ctl.sv
  D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/sources_1/imports/src/VeeRwolf/VeeR_EL2CoreComplex/lsu/el2_lsu_stbuf.sv
  D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/sources_1/imports/src/VeeRwolf/VeeR_EL2CoreComplex/lsu/el2_lsu_trigger.sv
  D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/sources_1/imports/src/VeeRwolf/VeeR_EL2CoreComplex/el2_mem.sv
  D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/sources_1/imports/src/VeeRwolf/VeeR_EL2CoreComplex/el2_pic_ctrl.sv
  D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/sources_1/imports/src/VeeRwolf/VeeR_EL2CoreComplex/el2_veer.sv
  D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/sources_1/imports/src/OtherSources/pulp-platform.org__common_cells_1.20.0/src/fifo_v3.sv
  D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/sources_1/imports/src/OtherSources/pulp-platform.org__common_cells_1.20.0/src/lzc.sv
  D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/sources_1/imports/src/VeeRwolf/VeeR_EL2CoreComplex/lib/mem_lib.sv
  D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/sources_1/imports/src/VeeRwolf/Peripherals/PMODD_controller/pmod_D_ctrlr.sv
  D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/sources_1/imports/src/OtherSources/pulp-platform.org__common_cells_1.20.0/src/rr_arb_tree.sv
  D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/sources_1/imports/src/OtherSources/pulp-platform.org__common_cells_1.20.0/src/spill_register.sv
  D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/sources_1/imports/src/VeeRwolf/Peripherals/PMODD_controller/ultrasonic_sensor.sv
  D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/sources_1/imports/src/VeeRwolf/VeeR_EL2CoreComplex/veer_el2_wrapper.sv
  D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/sources_1/imports/src/VeeRwolf/Peripherals/SystemController/veerwolf_syscon.sv
  D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/sources_1/imports/src/VeeRwolf/Peripherals/vga/vga_ctrlr.sv
  D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/sources_1/imports/src/rvfpgaboolean.sv
}
set_property file_type SystemVerilog [get_files D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/sources_1/imports/src/VeeRwolf/VeeR_EL2CoreComplex/include/el2_pdef.vh]
set_property is_global_include true [get_files D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/sources_1/imports/src/VeeRwolf/VeeR_EL2CoreComplex/include/el2_pdef.vh]
read_verilog -library xil_defaultlib {
  D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/sources_1/imports/src/VeeRwolf/Peripherals/jstk/ClkDiv_5Hz.v
  D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/sources_1/imports/src/VeeRwolf/Peripherals/jstk/ClkDiv_66_67kHz.v
  D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/sources_1/imports/src/VeeRwolf/Peripherals/jstk/PmodJSTK.v
  D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/sources_1/imports/src/VeeRwolf/Peripherals/jstk/PmodJSTK_Demo.v
  D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/sources_1/imports/src/VeeRwolf/Peripherals/jstk/SPImode0.v
  D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/sources_1/imports/src/VeeRwolf/Interconnect/AxiToWb/axi2wb.v
  D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/sources_1/imports/src/OtherSources/axi_ram.v
  D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/sources_1/imports/src/OtherSources/clk_gen_boolean.v
  D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/sources_1/imports/src/VeeRwolf/Peripherals/dcMotor/dc_motor_controller.v
  D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/sources_1/imports/src/VeeRwolf/BootROM/dpram64.v
  D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/sources_1/imports/src/VeeRwolf/Peripherals/vga/dtg.v
  D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/sources_1/imports/src/OtherSources/hdmi_tx_1.0/hdl/encode.v
  D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/sources_1/imports/src/VeeRwolf/Peripherals/gpio/gpio_top.v
  D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/sources_1/imports/src/OtherSources/hdmi_tx_1.0/hdl/hdmi_tx_v1_0.v
  D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/sources_1/imports/src/VeeRwolf/Peripherals/PMODD_controller/pmod_D_ctrlr_wrapper.v
  D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/sources_1/imports/src/VeeRwolf/Peripherals/ptc/ptc_top.v
  D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/sources_1/imports/src/VeeRwolf/Peripherals/uart/raminfr.v
  D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/sources_1/imports/src/OtherSources/hdmi_tx_1.0/hdl/serdes_10_to_1.v
  D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/sources_1/imports/src/VeeRwolf/Peripherals/servo/servo_controller.v
  D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/sources_1/imports/src/VeeRwolf/Peripherals/jstk/spiCtrl.v
  D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/sources_1/imports/src/OtherSources/hdmi_tx_1.0/hdl/srldelay.v
  D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/sources_1/imports/src/VeeRwolf/Peripherals/uart/uart_receiver.v
  D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/sources_1/imports/src/VeeRwolf/Peripherals/uart/uart_regs.v
  D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/sources_1/imports/src/VeeRwolf/Peripherals/uart/uart_rfifo.v
  D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/sources_1/imports/src/VeeRwolf/Peripherals/uart/uart_sync_flops.v
  D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/sources_1/imports/src/VeeRwolf/Peripherals/uart/uart_tfifo.v
  D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/sources_1/imports/src/VeeRwolf/Peripherals/uart/uart_top.v
  D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/sources_1/imports/src/VeeRwolf/Peripherals/uart/uart_transmitter.v
  D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/sources_1/imports/src/VeeRwolf/Peripherals/uart/uart_wb.v
  D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/sources_1/imports/src/VeeRwolf/veerwolf_core.v
  D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/sources_1/imports/src/VeeRwolf/Peripherals/vga/vga_ctrlr_wrapper.v
  D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/sources_1/imports/src/VeeRwolf/Interconnect/WishboneInterconnect/wb_intercon.v
  D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/sources_1/imports/src/VeeRwolf/BootROM/wb_mem_wrapper.v
  D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/sources_1/imports/src/VeeRwolf/Interconnect/WishboneInterconnect/wb_intercon_1.2.2-r1/rtl/verilog/wb_mux.v
}
read_ip -quiet D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all d:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.gen/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all d:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

read_ip -quiet D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/sources_1/ip/clk_wiz_2/clk_wiz_2.xci
set_property used_in_implementation false [get_files -all d:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.gen/sources_1/ip/clk_wiz_2/clk_wiz_2_board.xdc]
set_property used_in_implementation false [get_files -all d:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.gen/sources_1/ip/clk_wiz_2/clk_wiz_2.xdc]
set_property used_in_implementation false [get_files -all d:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.gen/sources_1/ip/clk_wiz_2/clk_wiz_2_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/constrs_1/imports/src/rvfpgaboolean.xdc
set_property used_in_implementation false [get_files D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/constrs_1/imports/src/rvfpgaboolean.xdc]

set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/utils_1/imports/synth_1/rvfpgaboolean.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top rvfpgaboolean -part xc7s50csga324-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef rvfpgaboolean.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file rvfpgaboolean_utilization_synth.rpt -pb rvfpgaboolean_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
