# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/sources_1/ip/clk_wiz_2/clk_wiz_2.xci
# IP: The module: 'clk_wiz_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.gen/sources_1/ip/clk_wiz_2/clk_wiz_2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.gen/sources_1/ip/clk_wiz_2/clk_wiz_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.gen/sources_1/ip/clk_wiz_2/clk_wiz_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: D:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.srcs/sources_1/ip/clk_wiz_2/clk_wiz_2.xci
# IP: The module: 'clk_wiz_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.gen/sources_1/ip/clk_wiz_2/clk_wiz_2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.gen/sources_1/ip/clk_wiz_2/clk_wiz_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/Fall_2023/ECE_540/final_proj/git/540_final_project/final_project/final_project.gen/sources_1/ip/clk_wiz_2/clk_wiz_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
